micronaut:
  application:
    name: httpclient

#tag::githubconfig[]
github:
  organization: micronaut-projects
  repo: micronaut-core
#end::githubconfig[]

endpoints:
  info:
    enabled: true
    sensitive: false